import { Intervention } from '../../interventions/types';

export const SHA_EMERGENCY_INTERVENTIONS: Intervention[] = [
  {
    id: 923,
    accessPoint: 'OP and IP',
    name: 'Cardiac/Respiratory Arrest',
    code: 'SHA-01-003',
    paymentMechanism: 'FEE FOR SERVICE',
    needsPreauth: false,
    needsManualPreauthApproval: false,
    needsDoctorAuthorization: false,
    overallTariff: '102915',
    globalPeriod: 0,
    kephLevelTarriff: '0',
    fund: 'ECCIF Only',
    fallBackOverallTariff: '0',
    numberOfDoctorsRequired: 0,
    tariffPerAdditionalKilometer: '0',
    level2Tariff: '0',
    level3Tariff: '0',
    level4Tariff: '0',
    level5Tariff: '0',
    level6Tariff: '0',
    requiresSurgicalPreauth: false,
    requiresRenalPreauth: false,
    requiresOncologyPreauth: false,
    requiresRadiologyPreauth: false,
    requiresOpticalPreauth: false,
    applicableSchemes: ['UHC'],
    applicableDocumentTypes: [
      'CLAIM_FORM',
      'DISCHARGE_SUMMARY',
      'FINAL_BILL',
      'IMAGING_REPORT',
      'LAB_RESULTS',
      'DISCHARGE_SUMMARY',
      'LAB_RESULTS',
      'IMAGING_REPORT',
      'CLAIM_FORM',
      'FINAL_BILL',
    ],
    optionalPreauthDocumentTypes: ['PREAUTH_FORM'],
    requiredClaimDocuments: [
      {
        key: 'CLAIM_FORM',
        label: 'Claim Form',
        anyOf: ['CLAIM_FORM'],
      },
      {
        key: 'DISCHARGE_SUMMARY',
        label: 'Discharge Summary',
        anyOf: ['DISCHARGE_SUMMARY'],
      },
      {
        key: 'FINAL_BILL',
        label: 'Final Bill',
        anyOf: ['FINAL_BILL'],
      },
      {
        key: 'IMAGING_REPORT',
        label: 'Imaging Report',
        anyOf: ['IMAGING_REPORT'],
      },
      {
        key: 'LAB_RESULTS',
        label: 'Lab Results',
        anyOf: ['LAB_RESULTS'],
      },
    ],
  },
  {
    id: 924,
    accessPoint: 'OP and IP',
    name: 'Major trauma',
    code: 'SHA-01-004',
    paymentMechanism: 'FEE FOR SERVICE',
    needsPreauth: false,
    needsManualPreauthApproval: false,
    needsDoctorAuthorization: false,
    overallTariff: '93042',
    globalPeriod: 0,
    kephLevelTarriff: '0',
    fund: 'ECCIF Only',
    fallBackOverallTariff: '0',
    numberOfDoctorsRequired: 0,
    tariffPerAdditionalKilometer: '0',
    level2Tariff: '0',
    level3Tariff: '0',
    level4Tariff: '0',
    level5Tariff: '0',
    level6Tariff: '0',
    requiresSurgicalPreauth: false,
    requiresRenalPreauth: false,
    requiresOncologyPreauth: false,
    requiresRadiologyPreauth: false,
    requiresOpticalPreauth: false,
    applicableSchemes: ['UHC'],
    applicableDocumentTypes: [
      'CLAIM_FORM',
      'DISCHARGE_SUMMARY',
      'FINAL_BILL',
      'IMAGING_REPORT',
      'LAB_RESULTS',
      'DISCHARGE_SUMMARY',
      'LAB_RESULTS',
      'IMAGING_REPORT',
      'CLAIM_FORM',
      'FINAL_BILL',
    ],
    optionalPreauthDocumentTypes: ['PREAUTH_FORM'],
    requiredClaimDocuments: [
      {
        key: 'CLAIM_FORM',
        label: 'Claim Form',
        anyOf: ['CLAIM_FORM'],
      },
      {
        key: 'DISCHARGE_SUMMARY',
        label: 'Discharge Summary',
        anyOf: ['DISCHARGE_SUMMARY'],
      },
      {
        key: 'FINAL_BILL',
        label: 'Final Bill',
        anyOf: ['FINAL_BILL'],
      },
      {
        key: 'IMAGING_REPORT',
        label: 'Imaging Report',
        anyOf: ['IMAGING_REPORT'],
      },
      {
        key: 'LAB_RESULTS',
        label: 'Lab Results',
        anyOf: ['LAB_RESULTS'],
      },
    ],
  },
  {
    id: 925,
    accessPoint: 'OP and IP',
    name: 'Shock states',
    code: 'SHA-01-005',
    paymentMechanism: 'FEE FOR SERVICE',
    needsPreauth: false,
    needsManualPreauthApproval: false,
    needsDoctorAuthorization: false,
    overallTariff: '74898',
    globalPeriod: 0,
    kephLevelTarriff: '0',
    fund: 'ECCIF Only',
    fallBackOverallTariff: '0',
    numberOfDoctorsRequired: 0,
    tariffPerAdditionalKilometer: '0',
    level2Tariff: '0',
    level3Tariff: '0',
    level4Tariff: '0',
    level5Tariff: '0',
    level6Tariff: '0',
    requiresSurgicalPreauth: false,
    requiresRenalPreauth: false,
    requiresOncologyPreauth: false,
    requiresRadiologyPreauth: false,
    requiresOpticalPreauth: false,
    applicableSchemes: ['UHC'],
    applicableDocumentTypes: [
      'CLAIM_FORM',
      'DISCHARGE_SUMMARY',
      'FINAL_BILL',
      'IMAGING_REPORT',
      'LAB_RESULTS',
      'DISCHARGE_SUMMARY',
      'LAB_RESULTS',
      'IMAGING_REPORT',
      'CLAIM_FORM',
      'FINAL_BILL',
    ],
    optionalPreauthDocumentTypes: ['PREAUTH_FORM'],
    requiredClaimDocuments: [
      {
        key: 'CLAIM_FORM',
        label: 'Claim Form',
        anyOf: ['CLAIM_FORM'],
      },
      {
        key: 'DISCHARGE_SUMMARY',
        label: 'Discharge Summary',
        anyOf: ['DISCHARGE_SUMMARY'],
      },
      {
        key: 'FINAL_BILL',
        label: 'Final Bill',
        anyOf: ['FINAL_BILL'],
      },
      {
        key: 'IMAGING_REPORT',
        label: 'Imaging Report',
        anyOf: ['IMAGING_REPORT'],
      },
      {
        key: 'LAB_RESULTS',
        label: 'Lab Results',
        anyOf: ['LAB_RESULTS'],
      },
    ],
  },
  {
    id: 926,
    accessPoint: 'OP and IP',
    name: 'Unconscious/Altered level of consciouness',
    code: 'SHA-01-006',
    paymentMechanism: 'FEE FOR SERVICE',
    needsPreauth: false,
    needsManualPreauthApproval: false,
    needsDoctorAuthorization: false,
    overallTariff: '20656',
    globalPeriod: 0,
    kephLevelTarriff: '0',
    fund: 'ECCIF Only',
    fallBackOverallTariff: '0',
    numberOfDoctorsRequired: 0,
    tariffPerAdditionalKilometer: '0',
    level2Tariff: '0',
    level3Tariff: '0',
    level4Tariff: '0',
    level5Tariff: '0',
    level6Tariff: '0',
    requiresSurgicalPreauth: false,
    requiresRenalPreauth: false,
    requiresOncologyPreauth: false,
    requiresRadiologyPreauth: false,
    requiresOpticalPreauth: false,
    applicableSchemes: ['UHC'],
    applicableDocumentTypes: [
      'CLAIM_FORM',
      'DISCHARGE_SUMMARY',
      'FINAL_BILL',
      'IMAGING_REPORT',
      'LAB_RESULTS',
      'DISCHARGE_SUMMARY',
      'LAB_RESULTS',
      'IMAGING_REPORT',
      'CLAIM_FORM',
      'FINAL_BILL',
    ],
    optionalPreauthDocumentTypes: ['PREAUTH_FORM'],
    requiredClaimDocuments: [
      {
        key: 'CLAIM_FORM',
        label: 'Claim Form',
        anyOf: ['CLAIM_FORM'],
      },
      {
        key: 'DISCHARGE_SUMMARY',
        label: 'Discharge Summary',
        anyOf: ['DISCHARGE_SUMMARY'],
      },
      {
        key: 'FINAL_BILL',
        label: 'Final Bill',
        anyOf: ['FINAL_BILL'],
      },
      {
        key: 'IMAGING_REPORT',
        label: 'Imaging Report',
        anyOf: ['IMAGING_REPORT'],
      },
      {
        key: 'LAB_RESULTS',
        label: 'Lab Results',
        anyOf: ['LAB_RESULTS'],
      },
    ],
  },
  {
    id: 927,
    accessPoint: 'OP and IP',
    name: 'Severe respiratory distress',
    code: 'SHA-01-007',
    paymentMechanism: 'FEE FOR SERVICE',
    needsPreauth: false,
    needsManualPreauthApproval: false,
    needsDoctorAuthorization: false,
    overallTariff: '14315',
    globalPeriod: 0,
    kephLevelTarriff: '0',
    fund: 'ECCIF Only',
    fallBackOverallTariff: '0',
    numberOfDoctorsRequired: 0,
    tariffPerAdditionalKilometer: '0',
    level2Tariff: '0',
    level3Tariff: '0',
    level4Tariff: '0',
    level5Tariff: '0',
    level6Tariff: '0',
    requiresSurgicalPreauth: false,
    requiresRenalPreauth: false,
    requiresOncologyPreauth: false,
    requiresRadiologyPreauth: false,
    requiresOpticalPreauth: false,
    applicableSchemes: ['UHC'],
    applicableDocumentTypes: [
      'CLAIM_FORM',
      'DISCHARGE_SUMMARY',
      'FINAL_BILL',
      'IMAGING_REPORT',
      'LAB_RESULTS',
      'DISCHARGE_SUMMARY',
      'LAB_RESULTS',
      'IMAGING_REPORT',
      'CLAIM_FORM',
      'FINAL_BILL',
    ],
    optionalPreauthDocumentTypes: ['PREAUTH_FORM'],
    requiredClaimDocuments: [
      {
        key: 'CLAIM_FORM',
        label: 'Claim Form',
        anyOf: ['CLAIM_FORM'],
      },
      {
        key: 'DISCHARGE_SUMMARY',
        label: 'Discharge Summary',
        anyOf: ['DISCHARGE_SUMMARY'],
      },
      {
        key: 'FINAL_BILL',
        label: 'Final Bill',
        anyOf: ['FINAL_BILL'],
      },
      {
        key: 'IMAGING_REPORT',
        label: 'Imaging Report',
        anyOf: ['IMAGING_REPORT'],
      },
      {
        key: 'LAB_RESULTS',
        label: 'Lab Results',
        anyOf: ['LAB_RESULTS'],
      },
    ],
  },
  {
    id: 928,
    accessPoint: 'OP and IP',
    name: 'Seizures/Status epilepticus',
    code: 'SHA-01-008',
    paymentMechanism: 'FEE FOR SERVICE',
    needsPreauth: false,
    needsManualPreauthApproval: false,
    needsDoctorAuthorization: false,
    overallTariff: '21106',
    globalPeriod: 0,
    kephLevelTarriff: '0',
    fund: 'ECCIF Only',
    fallBackOverallTariff: '0',
    numberOfDoctorsRequired: 0,
    tariffPerAdditionalKilometer: '0',
    level2Tariff: '0',
    level3Tariff: '0',
    level4Tariff: '0',
    level5Tariff: '0',
    level6Tariff: '0',
    requiresSurgicalPreauth: false,
    requiresRenalPreauth: false,
    requiresOncologyPreauth: false,
    requiresRadiologyPreauth: false,
    requiresOpticalPreauth: false,
    applicableSchemes: ['UHC'],
    applicableDocumentTypes: [
      'CLAIM_FORM',
      'DISCHARGE_SUMMARY',
      'FINAL_BILL',
      'IMAGING_REPORT',
      'LAB_RESULTS',
      'DISCHARGE_SUMMARY',
      'LAB_RESULTS',
      'IMAGING_REPORT',
      'CLAIM_FORM',
      'FINAL_BILL',
    ],
    optionalPreauthDocumentTypes: ['PREAUTH_FORM'],
    requiredClaimDocuments: [
      {
        key: 'CLAIM_FORM',
        label: 'Claim Form',
        anyOf: ['CLAIM_FORM'],
      },
      {
        key: 'DISCHARGE_SUMMARY',
        label: 'Discharge Summary',
        anyOf: ['DISCHARGE_SUMMARY'],
      },
      {
        key: 'FINAL_BILL',
        label: 'Final Bill',
        anyOf: ['FINAL_BILL'],
      },
      {
        key: 'IMAGING_REPORT',
        label: 'Imaging Report',
        anyOf: ['IMAGING_REPORT'],
      },
      {
        key: 'LAB_RESULTS',
        label: 'Lab Results',
        anyOf: ['LAB_RESULTS'],
      },
    ],
  },
  {
    id: 929,
    accessPoint: 'OP and IP',
    name: 'Acute coronary syndrome',
    code: 'SHA-01-009',
    paymentMechanism: 'FEE FOR SERVICE',
    needsPreauth: false,
    needsManualPreauthApproval: false,
    needsDoctorAuthorization: false,
    overallTariff: '106233',
    globalPeriod: 0,
    kephLevelTarriff: '0',
    fund: 'ECCIF Only',
    fallBackOverallTariff: '0',
    numberOfDoctorsRequired: 0,
    tariffPerAdditionalKilometer: '0',
    level2Tariff: '0',
    level3Tariff: '0',
    level4Tariff: '0',
    level5Tariff: '0',
    level6Tariff: '0',
    requiresSurgicalPreauth: false,
    requiresRenalPreauth: false,
    requiresOncologyPreauth: false,
    requiresRadiologyPreauth: false,
    requiresOpticalPreauth: false,
    applicableSchemes: ['UHC'],
    applicableDocumentTypes: [
      'CLAIM_FORM',
      'DISCHARGE_SUMMARY',
      'FINAL_BILL',
      'IMAGING_REPORT',
      'LAB_RESULTS',
      'DISCHARGE_SUMMARY',
      'LAB_RESULTS',
      'IMAGING_REPORT',
      'CLAIM_FORM',
      'FINAL_BILL',
    ],
    optionalPreauthDocumentTypes: ['PREAUTH_FORM'],
    requiredClaimDocuments: [
      {
        key: 'CLAIM_FORM',
        label: 'Claim Form',
        anyOf: ['CLAIM_FORM'],
      },
      {
        key: 'DISCHARGE_SUMMARY',
        label: 'Discharge Summary',
        anyOf: ['DISCHARGE_SUMMARY'],
      },
      {
        key: 'FINAL_BILL',
        label: 'Final Bill',
        anyOf: ['FINAL_BILL'],
      },
      {
        key: 'IMAGING_REPORT',
        label: 'Imaging Report',
        anyOf: ['IMAGING_REPORT'],
      },
      {
        key: 'LAB_RESULTS',
        label: 'Lab Results',
        anyOf: ['LAB_RESULTS'],
      },
    ],
  },
  {
    id: 930,
    accessPoint: 'OP and IP',
    name: 'Acute Cerebrovascular Accidents',
    code: 'SHA-01-010',
    paymentMechanism: 'FEE FOR SERVICE',
    needsPreauth: false,
    needsManualPreauthApproval: false,
    needsDoctorAuthorization: false,
    overallTariff: '106233',
    globalPeriod: 0,
    kephLevelTarriff: '0',
    fund: 'ECCIF Only',
    fallBackOverallTariff: '0',
    numberOfDoctorsRequired: 0,
    tariffPerAdditionalKilometer: '0',
    level2Tariff: '0',
    level3Tariff: '0',
    level4Tariff: '0',
    level5Tariff: '0',
    level6Tariff: '0',
    requiresSurgicalPreauth: false,
    requiresRenalPreauth: false,
    requiresOncologyPreauth: false,
    requiresRadiologyPreauth: false,
    requiresOpticalPreauth: false,
    applicableSchemes: ['UHC'],
    applicableDocumentTypes: [
      'CLAIM_FORM',
      'DISCHARGE_SUMMARY',
      'FINAL_BILL',
      'IMAGING_REPORT',
      'LAB_RESULTS',
      'DISCHARGE_SUMMARY',
      'LAB_RESULTS',
      'IMAGING_REPORT',
      'CLAIM_FORM',
      'FINAL_BILL',
    ],
    optionalPreauthDocumentTypes: ['PREAUTH_FORM'],
    requiredClaimDocuments: [
      {
        key: 'CLAIM_FORM',
        label: 'Claim Form',
        anyOf: ['CLAIM_FORM'],
      },
      {
        key: 'DISCHARGE_SUMMARY',
        label: 'Discharge Summary',
        anyOf: ['DISCHARGE_SUMMARY'],
      },
      {
        key: 'FINAL_BILL',
        label: 'Final Bill',
        anyOf: ['FINAL_BILL'],
      },
      {
        key: 'IMAGING_REPORT',
        label: 'Imaging Report',
        anyOf: ['IMAGING_REPORT'],
      },
      {
        key: 'LAB_RESULTS',
        label: 'Lab Results',
        anyOf: ['LAB_RESULTS'],
      },
    ],
  },
  {
    id: 931,
    accessPoint: 'OP and IP',
    name: 'Anti-Rabies',
    code: 'SHA-01-011',
    paymentMechanism: 'FEE FOR SERVICE',
    needsPreauth: false,
    needsManualPreauthApproval: false,
    needsDoctorAuthorization: false,
    overallTariff: '2600',
    globalPeriod: 0,
    kephLevelTarriff: '0',
    fund: 'ECCIF Only',
    fallBackOverallTariff: '0',
    numberOfDoctorsRequired: 0,
    tariffPerAdditionalKilometer: '0',
    level2Tariff: '0',
    level3Tariff: '0',
    level4Tariff: '0',
    level5Tariff: '0',
    level6Tariff: '0',
    requiresSurgicalPreauth: false,
    requiresRenalPreauth: false,
    requiresOncologyPreauth: false,
    requiresRadiologyPreauth: false,
    requiresOpticalPreauth: false,
    applicableSchemes: ['PMF', 'UHC'],
    applicableDocumentTypes: [
      'CLAIM_FORM',
      'DISCHARGE_SUMMARY',
      'FINAL_BILL',
      'IMAGING_REPORT',
      'LAB_RESULTS',
      'DISCHARGE_SUMMARY',
      'LAB_RESULTS',
      'IMAGING_REPORT',
      'CLAIM_FORM',
      'FINAL_BILL',
    ],
    optionalPreauthDocumentTypes: ['PREAUTH_FORM'],
    requiredClaimDocuments: [
      {
        key: 'CLAIM_FORM',
        label: 'Claim Form',
        anyOf: ['CLAIM_FORM'],
      },
      {
        key: 'DISCHARGE_SUMMARY',
        label: 'Discharge Summary',
        anyOf: ['DISCHARGE_SUMMARY'],
      },
      {
        key: 'FINAL_BILL',
        label: 'Final Bill',
        anyOf: ['FINAL_BILL'],
      },
      {
        key: 'IMAGING_REPORT',
        label: 'Imaging Report',
        anyOf: ['IMAGING_REPORT'],
      },
      {
        key: 'LAB_RESULTS',
        label: 'Lab Results',
        anyOf: ['LAB_RESULTS'],
      },
    ],
  },
  {
    id: 932,
    accessPoint: 'OP and IP',
    name: 'Anti-Snake Venom',
    code: 'SHA-01-012',
    paymentMechanism: 'FEE FOR SERVICE',
    needsPreauth: false,
    needsManualPreauthApproval: false,
    needsDoctorAuthorization: false,
    overallTariff: '6600',
    globalPeriod: 0,
    kephLevelTarriff: '0',
    fund: 'ECCIF Only',
    fallBackOverallTariff: '0',
    numberOfDoctorsRequired: 0,
    tariffPerAdditionalKilometer: '0',
    level2Tariff: '0',
    level3Tariff: '0',
    level4Tariff: '0',
    level5Tariff: '0',
    level6Tariff: '0',
    requiresSurgicalPreauth: false,
    requiresRenalPreauth: false,
    requiresOncologyPreauth: false,
    requiresRadiologyPreauth: false,
    requiresOpticalPreauth: false,
    applicableSchemes: ['PMF', 'UHC'],
    applicableDocumentTypes: [
      'CLAIM_FORM',
      'DISCHARGE_SUMMARY',
      'FINAL_BILL',
      'IMAGING_REPORT',
      'LAB_RESULTS',
      'DISCHARGE_SUMMARY',
      'LAB_RESULTS',
      'IMAGING_REPORT',
      'CLAIM_FORM',
      'FINAL_BILL',
    ],
    optionalPreauthDocumentTypes: ['PREAUTH_FORM'],
    requiredClaimDocuments: [
      {
        key: 'CLAIM_FORM',
        label: 'Claim Form',
        anyOf: ['CLAIM_FORM'],
      },
      {
        key: 'DISCHARGE_SUMMARY',
        label: 'Discharge Summary',
        anyOf: ['DISCHARGE_SUMMARY'],
      },
      {
        key: 'FINAL_BILL',
        label: 'Final Bill',
        anyOf: ['FINAL_BILL'],
      },
      {
        key: 'IMAGING_REPORT',
        label: 'Imaging Report',
        anyOf: ['IMAGING_REPORT'],
      },
      {
        key: 'LAB_RESULTS',
        label: 'Lab Results',
        anyOf: ['LAB_RESULTS'],
      },
    ],
  },
  {
    id: 1154,
    accessPoint: 'OP and IP',
    name: 'Chest Pain',
    code: 'SHA-01-013',
    paymentMechanism: 'FEE FOR SERVICE',
    needsPreauth: false,
    needsManualPreauthApproval: false,
    needsDoctorAuthorization: false,
    overallTariff: '107633',
    globalPeriod: 0,
    kephLevelTarriff: '0',
    fund: 'ECCIF Only',
    fallBackOverallTariff: '0',
    numberOfDoctorsRequired: 0,
    tariffPerAdditionalKilometer: '0',
    level2Tariff: '0',
    level3Tariff: '0',
    level4Tariff: '0',
    level5Tariff: '0',
    level6Tariff: '0',
    requiresSurgicalPreauth: false,
    requiresRenalPreauth: false,
    requiresOncologyPreauth: false,
    requiresRadiologyPreauth: false,
    requiresOpticalPreauth: false,
    applicableSchemes: ['PMF', 'UHC'],
    applicableDocumentTypes: [
      'CLAIM_FORM',
      'DISCHARGE_SUMMARY',
      'FINAL_BILL',
      'IMAGING_REPORT',
      'LAB_RESULTS',
      'DISCHARGE_SUMMARY',
      'LAB_RESULTS',
      'IMAGING_REPORT',
      'CLAIM_FORM',
      'FINAL_BILL',
    ],
    optionalPreauthDocumentTypes: ['PREAUTH_FORM'],
    requiredClaimDocuments: [
      {
        key: 'CLAIM_FORM',
        label: 'Claim Form',
        anyOf: ['CLAIM_FORM'],
      },
      {
        key: 'DISCHARGE_SUMMARY',
        label: 'Discharge Summary',
        anyOf: ['DISCHARGE_SUMMARY'],
      },
      {
        key: 'FINAL_BILL',
        label: 'Final Bill',
        anyOf: ['FINAL_BILL'],
      },
      {
        key: 'IMAGING_REPORT',
        label: 'Imaging Report',
        anyOf: ['IMAGING_REPORT'],
      },
      {
        key: 'LAB_RESULTS',
        label: 'Lab Results',
        anyOf: ['LAB_RESULTS'],
      },
    ],
  },
];
