import { ClaimVisitInvoince, VisitIntervention } from '../../visit/types';

export type PreviewProviderClaimDto = {
  consent_token: string;
};

export type ProviderClaimPreviewResponse = {
  id: string;
  workflow_state: string;
  claim_auth_status: string;
  total_claim_amount: string;
  total_claim_net_amount: string;
  total_claim_copay: string;
  total_claim_discount: string;
  total_claim_splits: string;
  is_negative: boolean;
  is_zero: boolean;
  created_by_name: string;
  invoices: ClaimVisitInvoince[];
  interventions: VisitIntervention[];
  claim_diagnoses: any[];
  claim_attachments: any[];
  claim_doctors: any[];
  patient_name: string;
  patient_number: string;
  member_number: string;
  scheme_code: string;
  scheme_name: string;
  provider_name: string;
  service_type: string;
  visit_start: string;
  number_of_invoices: number;
  diagnoses_count: number;
  claim_attachments_count: number;
  invoice_attachments_count: number;
  authorization_code: string;
};

export type PreviewPayerClaimDto = {
  guid?: string;
  provider_claim_no?: string;
};
export type ClaimDignosis = {
  guid: string;
  encounterGuid: string;
  encounter: number;
  siteCode: string;
  siteCodeType: string;
  name: string;
  intervention: number;
};
export type ClaimLine = {
  id: number;
  guid: string;
  name: string;
  quantity: string;
  intervention: number;
  interventionCode: string;
  interventionName: string;
  billFrom: string;
  billTo: string;
  unit: string;
  unitPrice: string;
  claimLineTotal: string;
  claimLineGrossTotal: string;
  approvedLineTotal: string;
  rejectedLineTotal: string;
  providerClaimLineNo: string;
  billingCode: string;
  chargeDate: string;
  workflowState: string;
  schemeCode: string;
  schemeName: string;
};
export type ClaimTransition = {
  id: number;
  guid: string;
  workflowStateFrom: string;
  workflowStateTo: string;
  transitionDate: string;
};
export type ClaimNote = {
  id: number;
  guid: string;
  note: string;
  author: string;
  source: string;
  workflowState: string;
};
export type ClaimIntervention = {
  id: number;
  guid: string;
  accessPoint: string;
  name: string;
  code: string;
  status: string;
  paymentMechanism: string;
  coverageLevel: string;
  applicableGender: string;
  applicableFacilityOwnership: string;
  usageFrequencyType: string;
  levelsApplicable: string | null;
  annualQuantityLimit: number;
  active: boolean;
  needsPreauth: boolean;
  needsManualPreauthApproval: boolean;
  needsDoctorAuthorization: boolean;
  needsMemberAuthorization: boolean;
  needApprovalBeforeClaimSubmission: boolean;
  isIntraMetro: boolean;
  managementTariffHasLimit: boolean;
  investigationTariffHasLimit: boolean;
  overallTariff: string;
  overallTariffHasLimit: boolean;
  benefit: number;
  kephLevelTarrif: string;
  preauthFinalised: boolean;
  requiresSurgicalPreauth: boolean;
  requiresRenalPreauth: boolean;
  requiresOncologyPreauth: boolean;
  requiresRadiologyPreauth: boolean;
  requiresOpticalPreauth: boolean;
  optionalDocumentType: any;
  requiredPreauthDocumentTypes: any;
  optionalPreauthDocumentTypes: any;
  applicableDocumentTypes: any[];
};
export type ClaimAuthorization = {
  id: number;
  guid: string;
  createdByName: string;
  providerName: string;
  authCode: string;
  beneficiaryName: string;
  beneficiaryCode: string;
  beneficiaryScheme: string;
  beneficiaryJoinDate: string;
  interventions: ClaimIntervention[];
  token: string;
  status: string;
  expiry: string;
  notes: string;
  benefitType: string;
  created: string;
  isOpen: boolean;
  isComplete: boolean;
  label: string;
  authorizationType: string[];
  beneficiaryNumber: string;
  preauthIds: any[];
  totalAuthorizedAmount: string;
  currentAvailableBalance: string;
  needsPreauth: boolean;
  isElective: boolean;
  overallPreauthFinalised: true;
  owner: number;
};
export type PayerClaimPreviewResponse = {
  pageSize: number;
  results: [
    {
      id: number;
      guid: string;
      authorization: ClaimAuthorization;
      billFrom: string;
      billTo: string;
      created: string;
      workflowState: string;
      workflowDisplayName: string;
      claimType: string;
      actualDeductableCopay: string;
      proposedValue: string;
      proposedValueLessCopays: string;
      totalCopayValue: string;
      trackingNumber: string;
      authToken: string;
      memberNumber: string;
      memberName: string;
      providerName: string;
      encounter: number;
      providerClaimNo: string;
      diagnoses: ClaimDignosis[];
      claimLines: ClaimLine[];
      claimTransitions: ClaimTransition[];
      claimNotes: ClaimNote[];
      owner: number;
      schemeName: string;
    },
  ];
};
